### ISSUE TITLE
Lyricue 4.0.7: MySQL crash?

### ISSUE THREAD

**Issue by claudep** [cjd/lyricue#7]
System recently upgraded from 14.04 to 16.04.
Lyricue 4.0.7 installed, a MySQL-related thing is crashing the program, see https://imagebin.ca/v/2tatQJlVuZcp (Sorry for language, it's not on my computer)
Any clue?

**Comment by cjd** [comment]
I think new versions of mysql changed the permission sets and so by default you can't check the current time (leading to those failures)
Can you please try running:

# mysql -uroot -p -e "grant all on lyricDb.\* to 'lyric'@'localhost'" mysql

And see if that helps?

**Comment by cjd** [comment]
Next thing to try is:
mysql -uroot -p -e "GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES, EXECUTE ON 'lyricDb.*' TO 'lyric@localhost'" mysql

**Comment by claudep** [comment]
Sorry neither command solved the issue :-(

**Comment by cjd** [comment]
I think I may have gotten the quoting wrong on that command.
try:
mysql -uroot -p -e "GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES, EXECUTE ON lyricDb.\* TO lyric@localhost" mysql

You may need to restart mysql for the change to take effect

**Comment by claudep** [comment]
I had the opportunity to physically access the machine today. I tried running manually the faulty query and got:

```
mysql> DELETE FROM status WHERE TIMEDIFF(NOW(),lastupdate) > '00:10:00';
 ERROR 1292 (22007): Truncated incorrect time value: '905:07:16'
```

The status table content is:

```
mysql> select * from status;
+-------------------+---------------+---------------------+---------+----------+-----+----------------+
| host              | title         | lastupdate          | profile | type     | ref | ip             |
+-------------------+---------------+---------------------+---------+----------+-----+----------------+
| sor-bureau:2346   | 0;0;0         | 2016-09-05 10:09:20 | Default | normal#  | 0   | 192.168.178.26 |
| sor-bureau:2347   | 0;0;0         | 2016-09-23 14:40:10 | Default | preview# | 0   | 192.168.1.148  |
| sor-portable:2346 | blank_bg0;0;0 | 2016-08-16 21:45:10 | Default | normal   | 748 | 127.0.0.1      |
| sor-portable:2347 | 0;0;0         | 2016-08-16 21:45:06 | Default | preview  | 743 | 127.0.0.1      |
+-------------------+---------------+---------------------+---------+----------+-----+----------------+
4 rows in set (0.00 sec)
```

When selecting with the same query, no problem:

```
mysql> select TIMEDIFF(NOW(),lastupdate) AS diff FROM status;
+-----------+
| diff      |
+-----------+
| 436:40:05 |
| 00:09:15  |
| 838:59:59 |
| 838:59:59 |
+-----------+
4 rows in set, 2 warnings (0.00 sec)
```

```
mysql> SELECT * FROM status WHERE TIMEDIFF(NOW(),lastupdate) > '00:10:00';
+-------------------+---------------+---------------------+---------+---------+-----+----------------+
| host              | title         | lastupdate          | profile | type    | ref | ip             |
+-------------------+---------------+---------------------+---------+---------+-----+----------------+
| sor-bureau:2346   | 0;0;0         | 2016-09-05 10:09:20 | Default | normal# | 0   | 192.168.178.26 |
| sor-portable:2346 | blank_bg0;0;0 | 2016-08-16 21:45:10 | Default | normal  | 748 | 127.0.0.1      |
| sor-portable:2347 | 0;0;0         | 2016-08-16 21:45:06 | Default | preview | 743 | 127.0.0.1      |
+-------------------+---------------+---------------------+---------+---------+-----+----------------+
3 rows in set, 2 warnings (0.00 sec)
```

Hopefully this will lead you to a possible fix!

**Comment by claudep** [comment]
Even after having manually cleared the status table, I'm still obtaining the same error from Lyricue, even if running the DELETE query manually doesn't produce any more errors.
Not that while Lyricue displays the error dialog, the status table is continually being updated in the background.

**Comment by claudep** [comment]
@cjd Does the description above ring a bell for you?

**Comment by claudep** [comment]
Joining a crashing session launched with `lyricue -dq`
[Lyricue crash.txt](https://github.com/cjd/lyricue/files/516332/Lyricue.crash.txt)

**Comment by cjd** [comment]
Sorry - missed your updates.
Can you dump your lyricDb and mysql databases via:

# mysqldump -uroot lyricDb

# mysqldump -uroot mysql

Then I'll try and reproduce the behaviour

**Comment by claudep** [comment]
The files have been sent privately.

**Comment by cjd** [comment]
Thanks for those.
Are you running multiple systems that are accessing lyricue?
Are the clocks in sync (or at least close) between all of them?
I've made some small changes to hopefully handle timediffs being too large (and reduce the other messages when scanning for available bible databases.
Can you grab a copy of the lyricue file from https://raw.githubusercontent.com/cjd/lyricue/master/src/lyricue  and then try manually running that one to see if it helps?

**Comment by claudep** [comment]
No, no multiple systems. I'll pass along the lyricue file and report, thanks.

**Comment by claudep** [comment]
Yes, it seems the latest version fixed the issue. Yeah \o/
