### ISSUE TITLE
Tag source repository with 4.0.13 release

### ISSUE THREAD

**Issue by alerque** [cjd/lyricue#8]
The source repository needs to be tagged with 4.0.13. I know you pushed that release to Ubuntu build servers, but other packaging this for other distros is very difficult without a proper tag.

While you're at it, could you please re-tag the entire set of releases –or at least the last few– with consistent tag names? Some of them are tagged "lyricue-X.Y.Z" and one "vX.Y.Z" and another "X.Y.Z". one of the latter two forms would be preferred as unpacking the archives looks a lot saner then. Having the package name in the tag is redundant information with the base package name. Right now the build source directory ends up looking like "lyricue-lyricue-4.0.12", which is just dirty. If the tags didn't have this redundant bit of information in them the archives served by Github wouldn't extract to crazy locations like that.

**Comment by cjd** [comment]
This should be done now.
I renamed the various tags to x.x.x format and created the new 4.0.13 one
Hopefully I did it in the right way ;)

**Comment by alerque** [comment]
Thanks, that definitely cleaned up the distro packaging process.
